import JSZip from 'jszip';
import { Workspace, EntityType } from '../types';
import { toast } from 'sonner';

// Mapeamento para Geração Dinâmica de Registros
const REGISTRY_MAP: Partial<Record<EntityType, { func: string, modClass: string, tlPath: string }>> = {
    [EntityType.ITEM]: { func: 'RegisterItems', modClass: 'ModItem', tlPath: 'ModItem.js' },
    [EntityType.NPC]: { func: 'RegisterNPCs', modClass: 'ModNPC', tlPath: 'ModNPC.js' },
    [EntityType.PROJECTILE]: { func: 'RegisterProjectiles', modClass: 'ModProjectile', tlPath: 'ModProjectile.js' },
    [EntityType.BUFF]: { func: 'RegisterBuffs', modClass: 'ModBuff', tlPath: 'ModBuff.js' },
    [EntityType.BIOME]: { func: 'RegisterBiomes', modClass: 'ModBiome', tlPath: 'ModBiome.js' },
    [EntityType.BACKGROUND]: { func: 'RegisterBackgrounds', modClass: 'ModBackgrounds', tlPath: 'ModBackgrounds.js' },
    [EntityType.CLOUD]: { func: 'RegisterClouds', modClass: 'ModCloud', tlPath: 'ModCloud.js' },
    [EntityType.MENU]: { func: 'RegisterMenus', modClass: 'ModMenu', tlPath: 'ModMenu.js' },
    [EntityType.SUBWORLD]: { func: 'RegisterSubworlds', modClass: 'Subworld', tlPath: 'Subworld.js' },
    [EntityType.TILE]: { func: 'RegisterTiles', modClass: 'ModTile', tlPath: 'ModTile.js' },
    [EntityType.SYSTEM]: { func: 'RegisterSystems', modClass: 'ModSystem', tlPath: 'ModSystem.js' },
    [EntityType.GLOBAL]: { func: 'RegisterGlobal', modClass: 'ModSystem', tlPath: 'ModSystem.js' },
};

// Categoria para Pasta Visual
const CATEGORY_TO_FOLDER: Record<string, string> = {
  [EntityType.ITEM]: 'Items',
  [EntityType.NPC]: 'NPCs',
  [EntityType.PROJECTILE]: 'Projectiles',
  [EntityType.BUFF]: 'Buffs',
  [EntityType.BIOME]: 'Biomes',
  [EntityType.BACKGROUND]: 'Backgrounds',
  [EntityType.CLOUD]: 'Clouds',
  [EntityType.GLOBAL]: 'Global',
  [EntityType.MENU]: 'Menus',
  [EntityType.SUBWORLD]: 'Subworlds',
  [EntityType.TILE]: 'Tiles',
  [EntityType.SYSTEM]: 'Systems',
  [EntityType.PET]: 'Pets',
  [EntityType.BLANK]: '' 
};

// Array completo do Framework TL (Adicionado Loaders e Modules)
const FRAMEWORK_FILES = [
    'GlobalHooks.js', 'GlobalItem.js', 'GlobalLoot.js', 'GlobalNPC.js',
    'GlobalProjectile.js', 'GlobalTile.js', 'ModAsset.js', 'ModBackgrounds.js',
    'ModBiome.js', 'ModBuff.js', 'ModCloud.js', 'ModGore.js', 'ModHooks.js',
    'ModImports.js', 'ModItem.js', 'ModLocalization.js', 'ModMenu.js',
    'ModNPC.js', 'ModPlayer.js', 'ModProjectile.js', 'ModRecipe.js',
    'ModSystem.js', 'ModTexture.js', 'ModTexturedType.js', 'NPCHappiness.js',
    'NPCLoot.js', 'NPCShop.js', 'NPCSpawnInfo.js', 'PlayerDB.js', 'ProjAI.js',
    'SceneEffectPriority.js', 'Subworld.js', 'WorldDB.js',
    
    'Core/BinarySerializer.js', 'Core/DatabaseManager.js', 'Core/FileManager.js',
    'Core/ModLoader.js', 'Core/Prototypes.js',
    
    'Enums/BiomeID.js', 'Enums/CloudID.js',
    
    'Hooks/Chat.js', 'Hooks/ItemHooks.js', 'Hooks/NPCHooks.js', 'Hooks/PlayerHooks.js', 
    'Hooks/ProjectileHooks.js', 'Hooks/WorldHooks.js', 'Hooks/SystemHooks.js', 'Hooks/UIHooks.js',
    
    'Loaders/CombinedLoader.js', 'Loaders/ItemLoader.js', 'Loaders/NPCLoader.js', 
    'Loaders/ProjectileLoader.js', 'Loaders/BuffLoader.js', 'Loaders/TileLoader.js', 'Loaders/BiomeLoader.js',
    
    'Modules/MathUtils.js', 'Modules/DrawingUtils.js', 'Modules/SoundUtils.js', 
    'Modules/CollisionUtils.js', 'Modules/WorldUtils.js'
];

const base64ToBlob = async (base64Data: string) => {
    const base64 = base64Data.split(',')[1];
    const byteCharacters = atob(base64);
    const byteNumbers = new Array(byteCharacters.length);
    for (let i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
    }
    const byteArray = new Uint8Array(byteNumbers);
    return new Blob([byteArray]);
};

export const buildMod = async (workspace: Workspace) => {
    const zip = new JSZip();

    // ==========================================
    // 1. ESTRUTURA BASE DO MOD
    // ==========================================
    const authorsFolder = zip.folder("Authors");
    const previewsFolder = zip.folder("Previews");
    
    // Icone e Previews/0.png
    if (workspace.icon && workspace.icon.startsWith('data:image')) {
        const iconBlob = await base64ToBlob(workspace.icon);
        zip.file("Icon.png", iconBlob);
        previewsFolder?.file("0.png", iconBlob);
    }

    // Autores (0.png, 1.png, etc)
    if (workspace.authors && workspace.authors.length > 0) {
        await Promise.all(workspace.authors.map(async (author, index) => {
            if (author.avatar && author.avatar.startsWith('data:image')) {
                authorsFolder?.file(`${index}.png`, await base64ToBlob(author.avatar));
            }
        }));
    }

    zip.file("README.txt", `Mod generated by LemonEngine IDE\n\nMod Name: ${workspace.name}\nVersion: ${workspace.version}\nDescription: ${workspace.description}`);
    
    // Settings.json
    zip.file("Settings.json", JSON.stringify({
        name: workspace.name,
        internalId: workspace.internalId,
        version: workspace.version,
        description: workspace.description,
        authors: workspace.authors.map(a => a.name)
    }, null, 2));

    const modFolder = zip.folder(`Modified/1.mod`);
    const modifiedFolder = zip.folder(`Modified`);
    if (!modFolder || !modifiedFolder) return;

    modifiedFolder.file(`1.json`, JSON.stringify({
        Id: 1,
        InternalName: workspace.internalId,
        Name: workspace.name,
        Author: workspace.authors.map(a => a.name).join(', '),
        Version: `${workspace.version}.0`,
        Description: workspace.description
    }, null, 2));

    const contentFolder = modFolder.folder("Content");
    const texturesFolder = modFolder.folder("Textures");
    const localizationFolder = modFolder.folder("Localization");
    const registerFolder = modFolder.folder("Register");
    const tlFolder = modFolder.folder("TL");

    // ==========================================
    // 2. CONTEÚDO E TEXTURAS (Esperando async)
    // ==========================================
    await Promise.all(workspace.entities.map(async (entity) => {
        if (!entity.internalName || !entity.code) return;

        const catFolder = CATEGORY_TO_FOLDER[entity.category];
        const subFolder = entity.folder ? `${entity.folder}/` : '';
        const filePath = catFolder ? `${catFolder}/${subFolder}${entity.internalName}.js` : `${subFolder}${entity.internalName}.js`;
        
        contentFolder?.file(filePath, entity.code);

        // O erro estava aqui: o Zip compilava antes dessa promessa terminar! Resolvido com Promise.all.
        if (entity.texture && entity.texture.startsWith('data:image')) {
            const texPath = `${catFolder ? catFolder + '/' : ''}${subFolder}${entity.internalName}.png`;
            texturesFolder?.file(texPath, await base64ToBlob(entity.texture));
        }
    }));

    // ==========================================
    // 3. GERAÇÃO DOS REGISTERS
    // ==========================================
    const entitiesByCategory = workspace.entities.reduce((acc, entity) => {
        if (!acc[entity.category]) acc[entity.category] = [];
        acc[entity.category].push(entity);
        return acc;
    }, {} as Record<string, typeof workspace.entities>);

    const registerCalls: string[] = [];

    Object.keys(REGISTRY_MAP).forEach(catKey => {
        const category = catKey as EntityType;
        const registryData = REGISTRY_MAP[category];
        const entities = entitiesByCategory[category] || [];

        if (registryData && entities.length > 0) {
            let imports = `import { ${registryData.modClass} } from './../TL/${registryData.tlPath}';\n\n`;
            let registers = `export function ${registryData.func}() {\n`;

            entities.forEach(entity => {
                const catFolder = CATEGORY_TO_FOLDER[entity.category];
                const subFolder = entity.folder ? `${entity.folder}/` : '';
                const path = catFolder ? `${catFolder}/${subFolder}` : subFolder;
                
                imports += `import { ${entity.internalName} } from './../Content/${path}${entity.internalName}.js';\n`;
                registers += `    ${registryData.modClass}.register(${entity.internalName});\n`;
            });

            registers += `}\n`;
            
            registerFolder?.file(`${registryData.func}.js`, imports + registers);
            registerCalls.push(registryData.func);
        }
    });

    let registerAllCode = `import { ModSystem } from './../TL/ModSystem.js';\nimport { ModLoader } from './../TL/Core/ModLoader.js';\n\n`;
    registerCalls.forEach(func => {
        registerAllCode += `import { ${func} } from './${func}.js';\n`;
    });

    registerAllCode += `\n// Register all mod content\nexport function RegisterAll() {\n    ModSystem.register(ModLoader);\n    \n`;
    registerCalls.forEach((func, idx) => {
        registerAllCode += `    ${func}(); // ${idx + 1}\n`;
    });
    registerAllCode += `}\n`;
    registerFolder?.file("RegisterAll.js", registerAllCode);

    // ==========================================
    // 4. LOCALIZATION (JSON)
    // ==========================================
    if (workspace.localization && Object.keys(workspace.localization).length > 0) {
        localizationFolder?.file("pt-BR.json", JSON.stringify(workspace.localization, null, 2));
    }

    // ==========================================
    // 5. INJETAR O FRAMEWORK
    // ==========================================
    await Promise.all(FRAMEWORK_FILES.map(async (file) => {
        try {
            const res = await fetch(`/framework/TL/${file}`);
            if (!res.ok) throw new Error("File not found");
            let fileContent = await res.text();

            if (fileContent.includes('//{hookinput}')) {
                const hookFileName = file.split('/').pop()?.replace('.js', '') || '';
                const enabledHooks = workspace.enabledHooks?.[hookFileName] || {};
                
                const hookEntries = Object.entries(enabledHooks)
                    .map(([hookName, isActive]) => `        ${hookName}: ${isActive}`)
                    .join(',\n');
                
                const hookReplacement = `static HookList = {\n${hookEntries}\n    };`;
                fileContent = fileContent.replace('//{hookinput}', hookReplacement);
            }

            tlFolder?.file(file, fileContent);
        } catch (e) {
            tlFolder?.file(file, `// TL Framework file stub: ${file}\nexport const ${file.split('/').pop()?.replace('.js', '')} = {};`);
        }
    }));

    const mainJsContent = workspace.entities.find(e => e.id === 'main')?.code || `import { RegisterAll } from './Register/RegisterAll.js';\n\nRegisterAll();\n`;
    modFolder.file("main.js", mainJsContent);

    const blob = await zip.generateAsync({ type: "blob" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${workspace.internalId || 'MyMod'}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
};